// work/part4/ng-to-do/src/app/page/todo/todo-input/todo-input.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Todo } from 'src/app/page/todo/model/todo';

@Component({
  selector: 'app-todo-input',
  templateUrl: './todo-input.component.html',
  styleUrls: ['./todo-input.component.scss']
})
export class TodoInputComponent implements OnInit {
  newTodo: Todo = new Todo();
  @Output('add') addEvent: EventEmitter<Todo> = new EventEmitter();

  constructor() { }

  ngOnInit() {
    console.log(this.newTodo)
  }

  addTodo() {
    let task = this.newTodo.task.trim();
    if (!task) {
      alert('Enter new task!');
      return false;
    }
    // 생성날짜를 최신으로 기록하기 위해서 객체를 새로 만들어서 사용한다.
    this.addEvent.emit(new Todo(task));
    // 입력창 초기화를 위해서 새 객체를 할당한다.
    this.newTodo = new Todo();
  }
}

<section>
  <form>
    <div class="input-group mb-2">
      <input type="text" class="form-control" placeholder="Enter your task" name="task" [(ngModel)]="newTodo.task">
      <span class="input-group-append">
        <button class="btn btn-outline-secondary px-4" type="button" (click)="addTodo()">
          <i class="fas fa-paper-plane"></i> Add
        </button>
      </span>
    </div>
  </form>
</section>

<!-- <h5>newTodo</h5>
<pre>{{newTodo | json}}</pre> -->

// work/part4/vue-to-do/src/components/TodoInput.vue
<template lang="html">

  <section class="src-components-todo-input">
    <div class="input-group mb-3">
      <input v-model="newTodo" type="text" class="form-control" placeholder="Type your task here...">
      <div class="input-group-append">
        <button v-on:click="addTodo" class="btn btn-outline-secondary" type="button" id="button-addon2">Add Todo</button>
      </div>
    </div>
  </section>

</template>

<script lang="js">

export default {
  name: 'src-components-todo-input',
  props: [],
  mounted() {

  },
  data() {
    return {
      newTodo: null
    }
  },
  methods: {
    addTodo(){
      if (typeof this.newTodo === 'string') {
        this.newTodo = this.newTodo.trim();
      }
      if (this.newTodo) {
        this.$emit('addTodo', this.newTodo);
        this.newTodo = null;
      } else {
        alert('할 일을 입력하세요.');
      }
    }
  },
  computed: {

  }
}
</script>

<style scoped>
.src-components-todo-input {}
</style>
