// work/part4/vue-to-do/src/components/TodoHeader.vue
<template lang="html">

  <section class="src-components-todo-header">
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">Todo List App</h1>
        <p class="lead">Manage your tasks easily.</p>
      </div>
    </div>
  </section>

</template>

<script lang="js">
export default {
  name: 'src-components-todo-header',
  props: [],
  mounted() {

  },
  data() {
    return {

    }
  },
  methods: {

  },
  computed: {

  }
}
</script>

<style scoped>
.src-components-todo-header {}
</style>

// work/part4/todo-react/src/components/todo/todo-header/TodoHeader.js
import React, { Component } from 'react';
import './TodoHeader.scss';

// class TodoHeader extends Component {
//   render() {
//     return (
//       <section>
//         <div className="jumbotron bg-white pb-2 mb-2 bg">
//           <h1 className="display-4">To Do List</h1>
//           <p className="lead">Manage your tasks easily.</p>
//         </div>
//       </section>
//     );
//   }
// }

// https://velopert.com/2994
const TodoHeader = (props) => {
    return (
      <section>
        <div className="jumbotron bg-white pb-2 mb-2 bg">
          <h1 className="display-4">To Do List</h1>
          <p className="lead">Manage your tasks easily.</p>
        </div>
      </section>
    );
};

export default TodoHeader;
