// work/part4/todo-react/src/components/todo/TodoComponent.js
import React, { Component } from 'react';
import './TodoComponent.scss';
import { Todo } from './model/todo';
import TodoHeader from './todo-header/TodoHeader';
import TodoInput from './todo-input/TodoInput';
import TodoList from './todo-list/TodoList';

class TodoComponent extends Component {
  constructor(props) {
      super(props);
      this.state = {
        todos: []
      };
      // 테스트를 위한 더미 데이터
      this.state.todos.push(new Todo('Walk the dog this evening'));
      this.state.todos.push(new Todo('Go shopping at 3 PM'));
      this.state.todos.push(new Todo('Sleep well tonight'));
  }
  
  addTodo = (todo) => {
    this.state.todos.push(todo);
    this.setState({
      todos: this.state.todos
    });
  }
  
  removeTodo = (id) => {
    let index = this.state.todos.findIndex(item => item.id === id);
    this.state.todos.splice(index, 1);
    this.setState({
      todos: this.state.todos
    });
  }
  
  updateTodo = (todo) => {
    let index = this.state.todos.findIndex(item => item.id === todo.id);
    this.state.todos.splice(index, 1, todo);
    this.setState({
      todos: this.state.todos
    });
  }
  
  render() {
    return (
      <div className="container">
        <TodoHeader></TodoHeader>
        <TodoInput add={this.addTodo}></TodoInput>
        <TodoList todos={this.state.todos} remove={this.removeTodo} update={this.updateTodo}></TodoList>
        
        {/*
          <pre>{JSON.stringify(this.state, null, 2)}</pre>
        */}
      </div>
    );
  }
}

export default TodoComponent;

// work/part4/ng-to-do/src/app/page/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from 'src/app/page/todo/model/todo';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.scss']
})
export class TodoComponent implements OnInit {
  todos: Todo[] = [];

  ngOnInit() {
    this.todos.push(new Todo('Walk the dog this evening'));
    this.todos.push(new Todo('Go shopping at 3 PM'));
    this.todos.push(new Todo('Sleep well tonight'));
  }

  addTodo(todo: Todo) {
    this.todos.push(todo);

    // todos는 참조를 취급하는 변수로써
    // 새 배열을 참조하도록 만들면 항상 이를 자식에게 이를 전달한다.
    // 그러므로 자식이 deep copy 방식을 사용하더라도
    // 부모로부터 새 데이터를 받을 수 있게 된다.
    // this.todos = [...this.todos];

    // XXX
    // this.flag = !this.flag;
  }

  removeTodo(id: string) {
    let index = this.todos.findIndex(item => item.id === id);
    this.todos.splice(index, 1);

    // XXX
    // this.flag = !this.flag;
  }

  updateTodo(todo: Todo) {
    let index = this.todos.findIndex(item => item.id === todo.id);
    this.todos.splice(index, 1, todo);

    // XXX
    // this.flag = !this.flag;
  }

  // XXX
  // flag: boolean = false;
}

<div class="container-fluid">
  <app-todo-header></app-todo-header>
  <app-todo-input (add)="addTodo($event)"></app-todo-input>
  <app-todo-list [todos]="todos" (remove)="removeTodo($event)" (update)="updateTodo($event)"></app-todo-list>
</div>

<!-- XXX
flag 값에 따라 자식 컴포넌트를 새로 만들면 부모의 데이터가 자식에게 항상 전달된다.
<div *ngIf="flag">
  <app-todo-list [todos]="todos" (remove)="removeTodo($event)" (update)="updateTodo($event)"></app-todo-list>
</div>
<div *ngIf="!flag">
  <app-todo-list [todos]="todos" (remove)="removeTodo($event)" (update)="updateTodo($event)"></app-todo-list>
</div> -->

<!-- <hr>
<h5>Parent</h5>
<pre>{{todos | json}}</pre> -->
